# Uncomment the next line to define a global platform for your project
    platform :ios, '18.0'

target 'Auth via Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auth via Firebase
  pod 'FirebaseAuth', '~> 11.7'

end
